# Generated by Django 3.0.3 on 2020-03-03 11:34

from django.db import migrations, models
import services.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('qty', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to=services.models.image_file_path)),
                ('base_unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('DISCONTINUED', 'Discontinued'), ('HOLD', 'Hold')], default='ACTIVE', max_length=30)),
            ],
        ),
    ]
