version: '3'

services:
  db:
    image: postgres:17-alpine
    container_name: pgdb
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=tidedbu
      - POSTGRES_PASSWORD=mysecretpassword 
      - POSTGRES_DB=tide
    networks:
      - backend
    ports:
      - "5432:5432/tcp"
  web:
    container_name: tide_web
    build: .
    tty: true
    #command: python /code/tidebilling/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    networks:
      - backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=pgdb
      - POSTGRES_DB=tide
      - POSTGRES_USER=tidedbu
      - POSTGRES_PASSWORD=mysecretpassword
    depends_on:
      - db

volumes:
  dbdata:
    driver: local

networks: 
  backend: