# Generated by Django 3.0.3 on 2020-03-03 11:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_auto_20200303_1134'),
        ('subscriptions', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=1000, unique=True)),
                ('order_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order_item_subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('price', models.FloatField()),
                ('qty', models.IntegerField(default=1)),
                ('subtotal', models.FloatField()),
                ('tax_amount', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('row_total', models.FloatField()),
                ('requiring_duration', models.DurationField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Sunpended'), ('HOLD', 'Hold')], default='ACTIVE', max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item_product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_price', models.FloatField()),
                ('price', models.FloatField()),
                ('qty', models.IntegerField(default=1)),
                ('subtotal', models.FloatField()),
                ('tax_amount', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('row_total', models.FloatField()),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('HOLD', 'Hold'), ('CANCELED', 'Canceled')], default='PROCESSING', max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order_status'),
        ),
    ]
