# Generated by Django 5.2.17 on 2026-08-13 07:20

import django.db.models.deletion
import tidebilling.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_archived_at_customer_is_archived_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default=tidebilling.money.default_currency, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=tidebilling.money.default_tax_rate, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer'),
        ),
    ]
