# Generated by Django 3.0.3 on 2020-03-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercontact',
            options={'verbose_name': 'Customers Contact', 'verbose_name_plural': 'Customers Contacts'},
        ),
    ]
