# Generated by Django 5.2.17 on 2026-08-13 07:20

import django.db.models.deletion
import tidebilling.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_archived_at_customer_is_archived_and_more'),
        ('invoices', '0003_alter_invoice_issue_date'),
        ('orders', '0002_alter_orderitem_options_order_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Document sequence',
                'verbose_name_plural': 'Document sequences',
            },
        ),
        migrations.AlterModelOptions(
            name='invoicehistory',
            options={'ordering': ['-changed_at'], 'verbose_name_plural': 'Invoice history'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default=tidebilling.money.default_currency, max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=tidebilling.money.default_tax_rate, max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('tax_amount__gte', 0), ('discount_amount__gte', 0), ('total_amount__gte', 0), ('paid_amount__gte', 0)), name='invoice_amounts_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='documentsequence',
            unique_together={('prefix', 'year')},
        ),
    ]
