# Generated by Django 3.0.3 on 2020-03-03 11:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('customers', '0002_auto_20200303_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription_flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('customer_name', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=300)),
                ('order_id', models.CharField(max_length=150)),
                ('order_item_id', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=30)),
                ('requiring_duration', models.DurationField(default=0)),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_plans',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('requiring_duration', models.DurationField(default=0)),
                ('price', models.FloatField(default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Sunpended'), ('HOLD', 'Hold')], default='ACTIVE', max_length=30)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('requiring_duration', models.DurationField(default=0)),
                ('price', models.FloatField(default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Sunpended'), ('CANCELLED', 'Cancelled'), ('HOLD', 'Hold')], default='ACTIVE', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.Subscription_plans')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.Service')),
            ],
        ),
    ]
